# Generated by Django 3.2.13 on 2022-12-02 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(verbose_name='키')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('test_date', models.DateField(verbose_name='검사일시')),
                ('total_body_water', models.FloatField(verbose_name='체수분(L)')),
                ('protein', models.FloatField(verbose_name='단백질(kg)')),
                ('minerals', models.FloatField(verbose_name='무기질(kg)')),
                ('body_fat_mass', models.FloatField(verbose_name='체지방량(kg)')),
                ('weight', models.FloatField(verbose_name='체중(kg)')),
                ('skeletal_muscle_mass', models.FloatField(verbose_name='골격근량(kg)')),
                ('body_mass_index', models.FloatField(verbose_name='BMI(kg/m^2)')),
                ('percent_body_fat', models.FloatField(verbose_name='체지방률(%)')),
                ('inbody_score', models.IntegerField(verbose_name='인바디 점수')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)], verbose_name='학년')),
                ('room', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='반')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='번호')),
                ('password', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='비밀번호')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('grade', 'room', 'number'), name='student_id'),
        ),
        migrations.AddField(
            model_name='inbody',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생번호'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생번호'),
        ),
    ]
