# Generated by Django 3.2.13 on 2022-12-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20221206_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.CharField(default='', max_length=32, verbose_name='패스워드 키'),
        ),
    ]
