# Generated by Django 3.2.13 on 2022-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbody',
            name='body_fat_mass',
            field=models.FloatField(null=True, verbose_name='체지방량(kg)'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='height',
            field=models.FloatField(verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='inbody_score',
            field=models.FloatField(null=True, verbose_name='인바디 점수'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='minerals',
            field=models.FloatField(null=True, verbose_name='무기질(kg)'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='protein',
            field=models.FloatField(null=True, verbose_name='단백질(kg)'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='skeletal_muscle_mass',
            field=models.FloatField(null=True, verbose_name='골격근량(kg)'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='total_body_water',
            field=models.FloatField(null=True, verbose_name='체수분(L)'),
        ),
    ]
