# Generated by Django 3.2.13 on 2022-12-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20221213_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='key',
            field=models.BinaryField(null=True, verbose_name='패스워드 키'),
        ),
    ]
