# Generated by Django 3.2.13 on 2022-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(verbose_name='시간'),
        ),
    ]
